version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 555516925462.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=555516925462.dkr.ecr.ap-northeast-1.amazonaws.com/test_cicd
      - IMAGE_TAG=latest  # Hoặc bạn có thể thay đổi tag nếu cần

  build:
    commands:
      - printf '[{"name":"test_cicd","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

  post_build:
    commands:
      # Không cần push image nữa, chỉ cần tạo imagedefinitions.jsonw

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
